# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'forget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_forgetpasswordwindow(object):
    def setupUi(self, forgetpasswordwindow):
        forgetpasswordwindow.setObjectName("forgetpasswordwindow")
        forgetpasswordwindow.setWindowModality(QtCore.Qt.NonModal)
        forgetpasswordwindow.resize(597, 403)
        forgetpasswordwindow.setMinimumSize(QtCore.QSize(330, 200))
        self.centralwidget = QtWidgets.QWidget(forgetpasswordwindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lbl_enail = QtWidgets.QLabel(self.centralwidget)
        self.lbl_enail.setObjectName("lbl_enail")
        self.horizontalLayout_2.addWidget(self.lbl_enail)
        self.txt_email = QtWidgets.QLineEdit(self.centralwidget)
        self.txt_email.setObjectName("txt_email")
        self.horizontalLayout_2.addWidget(self.txt_email)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btn_send = QtWidgets.QPushButton(self.centralwidget)
        self.btn_send.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_send.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout_3.addWidget(self.btn_send)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.txt_status = QtWidgets.QLabel(self.centralwidget)
        self.txt_status.setObjectName("txt_status")
        self.horizontalLayout_4.addWidget(self.txt_status)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        forgetpasswordwindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(forgetpasswordwindow)
        self.statusbar.setObjectName("statusbar")
        forgetpasswordwindow.setStatusBar(self.statusbar)

        self.retranslateUi(forgetpasswordwindow)
        QtCore.QMetaObject.connectSlotsByName(forgetpasswordwindow)

    def retranslateUi(self, forgetpasswordwindow):
        _translate = QtCore.QCoreApplication.translate
        forgetpasswordwindow.setWindowTitle(_translate("forgetpasswordwindow", "Login"))
        self.lbl_enail.setText(_translate("forgetpasswordwindow", "Please key in your email"))
        self.btn_send.setText(_translate("forgetpasswordwindow", "Send"))
        self.txt_status.setText(_translate("forgetpasswordwindow", "Waiting user key in email address"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    forgetpasswordwindow = QtWidgets.QMainWindow()
    ui = Ui_forgetpasswordwindow()
    ui.setupUi(forgetpasswordwindow)
    forgetpasswordwindow.show()
    sys.exit(app.exec_())
